Update detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
-if [ -f $1/.buildpacks ]; then
+#if [ -f $1/.buildpacks ]; then
   echo "Multipack"
   exit 0
-else
-  echo "Missing .buildpacks file"
-  exit 1
-fi
+#else
+#  echo "Missing .buildpacks file"
+#  exit 1
+#fi
